// Generated by Supabase TypeScript generator
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      ai_prompts: {
        Row: {
          content: string
          created_at: string
          description: string | null
          id: string
          industry: string | null
          is_active: boolean
          language: string
          name: string
          prompt_type: 'system' | 'qualification' | 'booking' | 'followup' | 'handoff' | 'custom'
          tenant_id: string | null
          updated_at: string
          variables: Json
          version: number
        }
        Insert: {
          content: string
          created_at?: string
          description?: string | null
          id?: string
          industry?: string | null
          is_active?: boolean
          language?: string
          name: string
          prompt_type: 'system' | 'qualification' | 'booking' | 'followup' | 'handoff' | 'custom'
          tenant_id?: string | null
          updated_at?: string
          variables?: Json
          version?: number
        }
        Update: {
          content?: string
          created_at?: string
          description?: string | null
          id?: string
          industry?: string | null
          is_active?: boolean
          language?: string
          name?: string
          prompt_type?: 'system' | 'qualification' | 'booking' | 'followup' | 'handoff' | 'custom'
          tenant_id?: string | null
          updated_at?: string
          variables?: Json
          version?: number
        }
      }
      appointments: {
        Row: {
          calendly_event_id: string | null
          calendar_synced: boolean
          contact_id: string
          conversation_id: string | null
          created_at: string
          duration_minutes: number
          id: string
          meeting_link: string | null
          meeting_type: string | null
          notes: string | null
          reminder_count: number
          reminder_sent: boolean
          scheduled_time: string
          status: 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no-show'
          tenant_id: string
          updated_at: string
        }
        Insert: {
          calendly_event_id?: string | null
          calendar_synced?: boolean
          contact_id: string
          conversation_id?: string | null
          created_at?: string
          duration_minutes?: number
          id?: string
          meeting_link?: string | null
          meeting_type?: string | null
          notes?: string | null
          reminder_count?: number
          reminder_sent?: boolean
          scheduled_time: string
          status?: 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no-show'
          tenant_id: string
          updated_at?: string
        }
        Update: {
          calendly_event_id?: string | null
          calendar_synced?: boolean
          contact_id?: string
          conversation_id?: string | null
          created_at?: string
          duration_minutes?: number
          id?: string
          meeting_link?: string | null
          meeting_type?: string | null
          notes?: string | null
          reminder_count?: number
          reminder_sent?: boolean
          scheduled_time?: string
          status?: 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no-show'
          tenant_id?: string
          updated_at?: string
        }
      }
      audit_logs: {
        Row: {
          action: string
          created_at: string
          id: string
          ip_address: string | null
          new_values: Json
          old_values: Json
          record_id: string | null
          table_name: string | null
          tenant_id: string | null
          user_agent: string | null
          user_id: string | null
        }
        Insert: {
          action: string
          created_at?: string
          id?: string
          ip_address?: string | null
          new_values: Json
          old_values: Json
          record_id?: string | null
          table_name?: string | null
          tenant_id?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
        Update: {
          action?: string
          created_at?: string
          id?: string
          ip_address?: string | null
          new_values?: Json
          old_values?: Json
          record_id?: string | null
          table_name?: string | null
          tenant_id?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
      }
      contacts: {
        Row: {
          assigned_to: string | null
          budget_range: string | null
          created_at: string
          email: string | null
          first_message_at: string | null
          id: string
          language: string
          last_message_at: string | null
          lead_score: number
          metadata: Json
          name: string | null
          qualification_status: 'unqualified' | 'qualified' | 'contacted' | 'converted'
          service_interest: string | null
          source: 'organic' | 'referral' | 'paid' | 'direct' | 'other'
          tags: string[]
          temperature: 'new' | 'warm' | 'hot' | 'cold' | 'booked' | 'lost'
          tenant_id: string
          timeline: 'urgent' | 'this-week' | 'this-month' | 'exploring' | 'not-specified' | null
          updated_at: string
          whatsapp_number: string
        }
        Insert: {
          assigned_to?: string | null
          budget_range?: string | null
          created_at?: string
          email?: string | null
          first_message_at?: string | null
          id?: string
          language?: string
          last_message_at?: string | null
          lead_score?: number
          metadata?: Json
          name?: string | null
          qualification_status?: 'unqualified' | 'qualified' | 'contacted' | 'converted'
          service_interest?: string | null
          source?: 'organic' | 'referral' | 'paid' | 'direct' | 'other'
          tags?: string[]
          temperature?: 'new' | 'warm' | 'hot' | 'cold' | 'booked' | 'lost'
          tenant_id: string
          timeline?: 'urgent' | 'this-week' | 'this-month' | 'exploring' | 'not-specified' | null
          updated_at?: string
          whatsapp_number: string
        }
        Update: {
          assigned_to?: string | null
          budget_range?: string | null
          created_at?: string
          email?: string | null
          first_message_at?: string | null
          id?: string
          language?: string
          last_message_at?: string | null
          lead_score?: number
          metadata?: Json
          name?: string | null
          qualification_status?: 'unqualified' | 'qualified' | 'contacted' | 'converted'
          service_interest?: string | null
          source?: 'organic' | 'referral' | 'paid' | 'direct' | 'other'
          tags?: string[]
          temperature?: 'new' | 'warm' | 'hot' | 'cold' | 'booked' | 'lost'
          tenant_id?: string
          timeline?: 'urgent' | 'this-week' | 'this-month' | 'exploring' | 'not-specified' | null
          updated_at?: string
          whatsapp_number?: string
        }
      }
      conversation_usage: {
        Row: {
          amount_due: number
          billing_month: string
          conversation_count: number
          created_at: string
          id: string
          overage_count: number
          overage_rate: number
          paid: boolean
          paid_at: string | null
          stripe_invoice_id: string | null
          tenant_id: string
          updated_at: string
        }
        Insert: {
          amount_due?: number
          billing_month: string
          conversation_count?: number
          created_at?: string
          id?: string
          overage_count?: number
          overage_rate?: number
          paid?: boolean
          paid_at?: string | null
          stripe_invoice_id?: string | null
          tenant_id: string
          updated_at?: string
        }
        Update: {
          amount_due?: number
          billing_month?: string
          conversation_count?: number
          created_at?: string
          id?: string
          overage_count?: number
          overage_rate?: number
          paid?: boolean
          paid_at?: string | null
          stripe_invoice_id?: string | null
          tenant_id?: string
          updated_at?: string
        }
      }
      conversations: {
        Row: {
          ai_confidence_avg: number | null
          contact_id: string
          conversation_window_end: string | null
          conversation_window_start: string
          created_at: string
          handoff_reason: string | null
          handled_by: string | null
          id: string
          is_active: boolean
          key_insights: Json
          message_count: number
          status: 'active' | 'handoff-requested' | 'human-handling' | 'closed'
          summary: string | null
          tenant_id: string
          updated_at: string
        }
        Insert: {
          ai_confidence_avg?: number | null
          contact_id: string
          conversation_window_end?: string | null
          conversation_window_start?: string
          created_at?: string
          handoff_reason?: string | null
          handled_by?: string | null
          id?: string
          is_active?: boolean
          key_insights?: Json
          message_count?: number
          status?: 'active' | 'handoff-requested' | 'human-handling' | 'closed'
          summary?: string | null
          tenant_id: string
          updated_at?: string
        }
        Update: {
          ai_confidence_avg?: number | null
          contact_id?: string
          conversation_window_end?: string | null
          conversation_window_start?: string
          created_at?: string
          handoff_reason?: string | null
          handled_by?: string | null
          id?: string
          is_active?: boolean
          key_insights?: Json
          message_count?: number
          status?: 'active' | 'handoff-requested' | 'human-handling' | 'closed'
          summary?: string | null
          tenant_id?: string
          updated_at?: string
        }
      }
      messages: {
        Row: {
          ai_confidence: number | null
          ai_intent: string | null
          ai_sentiment: string | null
          content: string
          conversation_id: string
          created_at: string
          direction: 'inbound' | 'outbound'
          handoff_reason: string | null
          id: string
          language: string | null
          metadata: Json
          requires_handoff: boolean
          sender_id: string | null
          sender_type: 'contact' | 'ai' | 'human'
          tenant_id: string
          twilio_message_sid: string | null
        }
        Insert: {
          ai_confidence?: number | null
          ai_intent?: string | null
          ai_sentiment?: string | null
          content: string
          conversation_id: string
          created_at?: string
          direction: 'inbound' | 'outbound'
          handoff_reason?: string | null
          id?: string
          language?: string | null
          metadata?: Json
          requires_handoff?: boolean
          sender_id?: string | null
          sender_type: 'contact' | 'ai' | 'human'
          tenant_id: string
          twilio_message_sid?: string | null
        }
        Update: {
          ai_confidence?: number | null
          ai_intent?: string | null
          ai_sentiment?: string | null
          content?: string
          conversation_id?: string
          created_at?: string
          direction?: 'inbound' | 'outbound'
          handoff_reason?: string | null
          id?: string
          language?: string | null
          metadata?: Json
          requires_handoff?: boolean
          sender_id?: string | null
          sender_type?: 'contact' | 'ai' | 'human'
          tenant_id?: string
          twilio_message_sid?: string | null
        }
      }
      rate_limits: {
        Row: {
          created_at: string
          id: string
          message_count: number
          tenant_id: string
          whatsapp_number: string
          window_duration_seconds: number
          window_start: string
        }
        Insert: {
          created_at?: string
          id?: string
          message_count?: number
          tenant_id: string
          whatsapp_number: string
          window_duration_seconds?: number
          window_start?: string
        }
        Update: {
          created_at?: string
          id?: string
          message_count?: number
          tenant_id?: string
          whatsapp_number?: string
          window_duration_seconds?: number
          window_start?: string
        }
      }
      tenants: {
        Row: {
          ai_model: string
          ai_provider: 'anthropic' | 'openai'
          business_hours: Json
          calendly_api_key: string | null
          calendly_event_url: string | null
          company_name: string
          created_at: string
          faqs: Json
          id: string
          industry: 'real-estate' | 'automotive' | 'home-services' | 'medical' | 'other'
          language: string[]
          monthly_conversation_limit: number
          services: Json
          setup_completed: boolean
          setup_fee_paid: boolean
          stripe_customer_id: string | null
          subscription_status: 'trial' | 'active' | 'cancelled' | 'past_due'
          subscription_tier: 'starter' | 'growth' | 'scale' | 'enterprise'
          twilio_account_sid: string | null
          twilio_auth_token: string | null
          twilio_whatsapp_number: string | null
          updated_at: string
        }
        Insert: {
          ai_model?: string
          ai_provider?: 'anthropic' | 'openai'
          business_hours?: Json
          calendly_api_key?: string | null
          calendly_event_url?: string | null
          company_name: string
          created_at?: string
          faqs?: Json
          id?: string
          industry?: 'real-estate' | 'automotive' | 'home-services' | 'medical' | 'other'
          language?: string[]
          monthly_conversation_limit?: number
          services?: Json
          setup_completed?: boolean
          setup_fee_paid?: boolean
          stripe_customer_id?: string | null
          subscription_status?: 'trial' | 'active' | 'cancelled' | 'past_due'
          subscription_tier: 'starter' | 'growth' | 'scale' | 'enterprise'
          twilio_account_sid?: string | null
          twilio_auth_token?: string | null
          twilio_whatsapp_number?: string | null
          updated_at?: string
        }
        Update: {
          ai_model?: string
          ai_provider?: 'anthropic' | 'openai'
          business_hours?: Json
          calendly_api_key?: string | null
          calendly_event_url?: string | null
          company_name?: string
          created_at?: string
          faqs?: Json
          id?: string
          industry?: 'real-estate' | 'automotive' | 'home-services' | 'medical' | 'other'
          language?: string[]
          monthly_conversation_limit?: number
          services?: Json
          setup_completed?: boolean
          setup_fee_paid?: boolean
          stripe_customer_id?: string | null
          subscription_status?: 'trial' | 'active' | 'cancelled' | 'past_due'
          subscription_tier?: 'starter' | 'growth' | 'scale' | 'enterprise'
          twilio_account_sid?: string | null
          twilio_auth_token?: string | null
          twilio_whatsapp_number?: string | null
          updated_at?: string
        }
      }
      users: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string
          full_name: string | null
          id: string
          is_active: boolean
          last_login_at: string | null
          notification_preferences: Json
          password_hash: string
          phone_number: string | null
          role: 'owner' | 'admin' | 'agent' | 'viewer'
          tenant_id: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email: string
          full_name?: string | null
          id?: string
          is_active?: boolean
          last_login_at?: string | null
          notification_preferences?: Json
          password_hash: string
          phone_number?: string | null
          role?: 'owner' | 'admin' | 'agent' | 'viewer'
          tenant_id: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string
          full_name?: string | null
          id?: string
          is_active?: boolean
          last_login_at?: string | null
          notification_preferences?: Json
          password_hash?: string
          phone_number?: string | null
          role?: 'owner' | 'admin' | 'agent' | 'viewer'
          tenant_id?: string
          updated_at?: string
        }
      }
      webhook_events: {
        Row: {
          created_at: string
          error_message: string | null
          event_type: string
          id: string
          idempotency_key: string
          max_retries: number
          next_retry_at: string | null
          payload: Json
          processed: boolean
          processed_at: string | null
          retry_count: number
          source: 'twilio' | 'calendly' | 'stripe'
          tenant_id: string | null
        }
        Insert: {
          created_at?: string
          error_message?: string | null
          event_type: string
          id?: string
          idempotency_key?: string
          max_retries?: number
          next_retry_at?: string | null
          payload: Json
          processed?: boolean
          processed_at?: string | null
          retry_count?: number
          source: 'twilio' | 'calendly' | 'stripe'
          tenant_id?: string | null
        }
        Update: {
          created_at?: string
          error_message?: string | null
          event_type?: string
          id?: string
          idempotency_key?: string
          max_retries?: number
          next_retry_at?: string | null
          payload?: Json
          processed?: boolean
          processed_at?: string | null
          retry_count?: number
          source?: 'twilio' | 'calendly' | 'stripe'
          tenant_id?: string | null
        }
      }
    }
    Views: {
      conversation_summary: {
        Row: {
          contact_name: string | null
          contact_id: string
          conversation_start: string
          id: string
          last_message_at: string | null
          lead_score: number
          message_count: number
          status: string
          tenant_id: string
          temperature: string
          whatsapp_number: string
        }
        Insert: never
        Update: never
      }
      tenant_usage_stats: {
        Row: {
          company_name: string
          current_month_conversations: number
          is_over_limit: boolean
          monthly_conversation_limit: number
          overage: number
          subscription_tier: string
          tenant_id: string
        }
        Insert: never
        Update: never
      }
    }
    Functions: {
      close_conversation_windows: {
        Args: Record<PropertyKey, never>
        Returns: void
      }
      decrypt_sensitive_data: {
        Args: {
          encrypted_data: string
        }
        Returns: string
      }
      encrypt_sensitive_data: {
        Args: {
          data: string
        }
        Returns: string
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
